wireplumber.components = [
  {
    name = device/autoswitch-headphones-profile.lua, type = script/lua
    provides = hooks.device.profile.autoswitch-headphones
  }
]

wireplumber.profiles = {
  main = {
    hooks.device.profile.autoswitch-headphones = required
  }
}
